[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
env_logger = "0.10.0"
log = "0.4.17"

[dependencies.tokio]
version = "1.22.0"
features = ["full"]
